# Numpy

In [2]:
import numpy as np
mylist = [1, 2, 3, 4, 5]
arr = np.array(mylist)
print(arr)

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [7]:
list1 =  [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11, 12, 13, 14, 15]
arr2 = np.array([list1, list2, list3])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
arr2.shape

(3, 5)

In [9]:
arr2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

### indexing

In [10]:
arr2[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
arr2[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [14]:
arr[2:]=500

In [15]:
arr

array([  1,   2, 500, 500, 500])

### condition in array

In [16]:
arr<2

array([ True, False, False, False, False])

In [17]:
arr*2

array([   2,    4, 1000, 1000, 1000])

In [19]:
arr/2

array([  0.5,   1. , 250. , 250. , 250. ])

In [21]:
arr[arr<300

array([1, 2])